title: "Bayesian Analysis of COVID Origins"
theme: jekyll-theme-minimal
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-readme-index
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links
include:
  - "*.txt"
  - "*.csv"
  - "*.md"
  - "*.xlsx"
  - "*.dta"
  - "*.do"
  - "*.tif"
exclude:
  - node_modules
  - vendor
verbose: true
relative_links:
  enabled: true
  collections: true
